kouprlabs/voltaserve

api/router/file_router.go
ui/src/components/file/list/item/icon/processing-badge.tsx
ui/src/components/file/toolbar.tsx
ui/src/components/file/upload/worker.ts

Upload Folder Button

---

ui/src/components/file/list/item/icon/icon-badge/icon-badge-error.tsx

chore: update icon-badge-error.tsx

---

api/router/file_router.go
conversion/pipeline/audio_video_pipeline.go
conversion/pipeline/glb_pipeline.go
conversion/pipeline/image_pipeline.go
conversion/pipeline/insights_pipeline.go
conversion/pipeline/mosaic_pipeline.go
conversion/pipeline/office_pipeline.go
conversion/pipeline/pdf_pipeline.go
conversion/pipeline/zip_pipeline.go
conversion/processor/pdf_processor.go
conversion/processor/video_processor.go
webdav/handler/method_put.go
webdav/main.go

This will fix a lot of troubles:
1) In WebDAV's PUT method, temporary files were not deleted
2) In many occurrences, the check for it a temporary file exist was wrong.
3) Remove a mutex that is not really required.
Closes: #153
Closes: #154

fix: temporary files not deleted, correctly check if files exist

---

ui/src/components/account/menu/account-menu-active-circle.tsx
ui/src/components/account/menu/account-menu-avatar-button.tsx
ui/src/pages/account/account-layout.tsx

fix(ui): show circle around active profile image when active

---

migrations/src/lib.rs
migrations/src/m20240718_000002_create_organization.rs
migrations/src/models/v1.rs
migrations/src/models/v1/organization.rs
postgres/schema.sql

Adds the organization table and its associated organization_user join table for user membership.

feat(migration): create organization table and join table for membership

---

ui/src/components/account/menu/account-menu-avatar-button.tsx

fix(ui): account notification glitch

---

.github/workflows/lint-idp.yml
.github/workflows/lint-ui.yml

ci: add TypeScript compiler step to UI and IdP

---

conversion/identifier/file_identifier.go

- feat: support `.pages` Apple Pages files.
- feat: support `.numbers` Apple Numbers files.
- feat: support `.key` Apple Keynote files.
Closes #173

feat(conversion): support Apple documents

---

docker-compose.yml
idp/Dockerfile

chore: add migrations to Docker Compose file

---

webdav/handler/method_mkcol.go

- fix: do a no-op when receiving the error `file_with_similar_name_exists` on `MKCOL`.
Closes #187

fix(webdav): compatibiilty with Joplin

---

api/router/mosaic_router.go

- fix(api): Mosaic is not storing its own file extension, it assumes it can be always taken from preview data, so in case ImageMagick fails and there is no preview, we fallback to original, but there is an edge case, if the original is a TIFF and there is no preview (because of failing ImageMagick) then falling back to original is wrong, but this is a temporary fix until we replace ImageMagick with native Go.

fix(api): support mosaic without preview

---

api/errorpkg/error_creators.go
ui/src/pages/group/group-settings-page.tsx
ui/src/pages/organization/organization-settings-page.tsx
ui/src/pages/workspace/workspace-settings-page.tsx

refactor: UI adjustments and refactoring

---

.github/workflows/check-on-pr-console.yml

fix: added W503 line break before binary operator ignore 

---

api/infra/postgres.go
api/router/file_router.go
api/router/group_router.go
api/router/insights_router.go
api/router/invitation_router.go
api/router/organization_router.go
api/router/snapshot_router.go
api/router/task_router.go
api/router/user_router.go
api/router/workspace_router.go

fix(ui): postgres too many clients error

---

console/api/routers/group.py
console/api/routers/organization.py
console/api/routers/workspace.py
idp/src/infra/admin-requests.ts
idp/src/user/service.ts
ui/src/lib/helpers/picture.ts
ui/src/pages/account/account-invitations-page.tsx
ui/src/pages/console/console-panel-groups.tsx
ui/src/pages/console/console-panel-organizations.tsx
ui/src/pages/console/console-panel-users.tsx
ui/src/pages/console/console-panel-workspaces.tsx

fix(misc): various issues

---

api/infra/range.go
api/router/file_router.go
api/service/file_service.go
webdav/client/api_client/file_client.go
webdav/handler/method_get.go
webdav/handler/method_propfind.go

fix(misc): optimized video streaming for WebDAV

---

api/helper/path.go
api/repo/file_repo.go
api/router/file_router.go
api/service/file_service.go

fix(api): create snapshot on overwrite

---

console/Dockerfile
console/api/database/group.py
console/api/database/organization.py
console/api/database/workspace.py
console/api/dependencies/jwt.py
console/api/dependencies/user.py
console/api/models/group.py
console/api/models/organization.py
console/api/models/workspace.py
console/api/routers/group.py
console/api/routers/organization.py
console/api/routers/workspace.py
ui/src/client/console/console.ts
ui/src/pages/console/console-panel-groups.tsx
ui/src/pages/console/console-panel-organizations.tsx
ui/src/pages/console/console-panel-users.tsx
ui/src/pages/console/console-panel-workspaces.tsx

feat(console): show owner badge on resources

---

ui/src/components/account/account-theme-switcher.tsx
ui/src/local-storage/index.ts
ui/src/pages/root-page.tsx

fix(ui): system theme support

---

api/infra/s3.go
api/router/validation.go
api/service/constants.go
api/service/file_service.go
api/service/snapshot_service.go
api/service/task_service.go
ui/src/client/api/task.ts
ui/src/components/file/info/file-info-item-count.tsx
ui/src/components/task/task-drawer.tsx
ui/src/components/task/task-list.tsx

fix(api): file deletion stability

---

.github/workflows/build-api.yml
.github/workflows/build-console.yml
.github/workflows/build-conversion.yml
.github/workflows/build-idp.yml
.github/workflows/build-language.yml
.github/workflows/build-migrations.yml
.github/workflows/build-mosaic.yml
.github/workflows/build-ui.yml
.github/workflows/build-webdav.yml

ci(misc): Docker latest tag points to latest release

---

idp/.env
idp/src/account/router.ts
idp/src/account/service.ts
idp/src/config/config.ts
idp/src/config/types.ts
idp/src/error/core.ts
idp/src/error/creators.ts
idp/src/infra/mail.ts
idp/src/token/service.ts
idp/src/user/model.ts
idp/src/user/repo.ts
idp/src/user/router.ts
idp/src/user/service.ts
migrations/src/lib.rs
migrations/src/m20250420_000001_add_user_strategy_column.rs
migrations/src/models/v1/user.rs

feat(idp): simultaneous auth strategies
